esphome:
  name: doorbell
  friendly_name: Звонок

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT

  ap:
    ssid: "Doorbell"
    password: "xxx"

psram:
  mode: octal

i2c:
  - id: camera_i2c
    sda: GPIO40
    scl: GPIO39

esp32_camera:
  id: espcam
  name: "Звонок"
  icon: "mdi:doorbell-video"
  external_clock:
    pin: GPIO10
    frequency: 10MHz
  i2c_id: camera_i2c
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  frame_buffer_count: 2
  resolution: 800X600
  max_framerate: 10fps
  idle_framerate: 1fps
  vertical_flip: False
  horizontal_mirror: False

camera_encoder:
  quality: 10
  buffer_size: 2097152
  buffer_expand_size: 2097152

output:
  # Светодиод кнопки
  - platform: ledc
    pin: GPIO8
    id: led

light:
  - platform: monochromatic
    output: led
    id: led_pulse
    effects:
    - pulse:
        update_interval: 3s
        min_brightness: 0%
        max_brightness: 80%

binary_sensor:
  - platform: gpio
    id: press
    internal: True
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - light.turn_on:
            id: led_pulse
            effect: pulse
        - light.turn_off:
            id: led_pulse

  - platform: template
    name: "Кнопка"
    icon: "mdi:radiobox-marked"
    id: tresshold
    lambda: |-
      return id(press).state;
    filters:
      - delayed_off: 300s
